"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"
# right_format = "$git_metrics"
command_timeout = 500

[directory]
format = "[$path]($style) "

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[git_branch]
symbol = ""
format = '[$symbol $branch ]($style)'

[git_status]
disabled = false
format = '([$ahead_behind]($style) )'
style = 'bold yellow'

ahead = '⇡'
behind = '⇣'
diverged = ''

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
